export const CHARACTER_LIMIT = 50_000;
export const DEFAULT_TASK_TIMEOUT = 300_000; // 5 min
export const CLONE_TASK_TIMEOUT = 600_000; // 10 min — clones can be slow
export const TASK_POLL_INTERVAL = 2_000; // 2 seconds
export const GUEST_EXEC_TIMEOUT = 60_000; // 1 min for command execution
export const VMID_RANGE = { min: 100, max: 999_999_999 };

export const ENV = {
  PROXMOX_HOST: "PROXMOX_HOST",
  PROXMOX_TOKEN_ID: "PROXMOX_TOKEN_ID",
  PROXMOX_TOKEN_SECRET: "PROXMOX_TOKEN_SECRET",
  PROXMOX_USER: "PROXMOX_USER",
  PROXMOX_PASSWORD: "PROXMOX_PASSWORD",
  PROXMOX_DEFAULT_NODE: "PROXMOX_DEFAULT_NODE",
  PROXMOX_DEFAULT_STORAGE: "PROXMOX_DEFAULT_STORAGE",
  TRANSPORT: "TRANSPORT",
  PORT: "PORT",
} as const;
